colaboradores_por_departamento = {
    'Mauro Pereces Macedo': ['CSA - BH'],
    'Douglas Leite': ['CSA - BH'],
    'Julliana Cristina Bertoni': ['Financeiro'],
    'Juliana Silva Casagrande': ['Contabilidade'],
    'Leila Oliveira': ['Assessoria Jurídica'],
    'Eduardo dos Santos Lopes': ['CSA - CTG'],
    'Jaqueline Andrade Fonseca': ['CSA - GZ'],
    'Sergio da Silva Santos': ['Suprimentos', 'Administrativo'],
    'Rodrigo Mourão': ['Estratégia e Novos Negócios'],
    'Marcela Poeiras': ['Sustentabilidade'],
    'Karla Camargos Souza': ['CSA - DV'],
    'Fabricio de Paula Martins': ['CSA - NL'],
    'Karinne Dias': ['Departamento de Pessoal'],
    'Matheus Tine': ['Recursos Humanos'],
    'Diego Dias da Cruz': ['Departamento de Pessoal'],
    'Dayse Araújo Dutra': ['Assistência Social'],
    'Hudson Oliveira Leite': ['Tecnologia da Informação'],
    'Ana Carolina Soraggi': ['Administrativo'],
    'Clarissa Felix Azevedo': ['Internacionalização'],
    'Marcelo Viana Costa': ['EPSA'],
    'Amanda Macedo Fernandes': ['Financeiro'],
    'Ricardo Frederico Gouveia': ['Tecnologia da Informação'],
    'Patricia Nogueira Ferreira': ['ILALI'],
    'Ricardo Augusto Loureiro': ['Coordenação de Manutenção'],
    'Michelle Ribeiro Neves': ['AIACOM'],
    'Ana Rita Duarte de Faria': ['Comunicação e Marketing', 'Relacionamento com o Cliente'],
    'Edna Claudia Nascimento': ['ADEODATO'],
    'Aline Marian Duarte': ['Comunicação e Marketing'],
    'William Fernando Dias': ['Administrativo'],
    'Pablo Ronam João': ['CSA - CTG'],
    'Rafael Coelho Ferreira': ['Assessoria Jurídica'],
    'Miryam Laila Ferreira': ['Gestão de Documentos'],
    'Taianny Souza Pinto': ['CSA - DV'],
    'Luciana Alves Faria': ['Tecnologia da Informação'],
    'Mateus Gomes da Silva': ['ILALI'],
    'Jonathan Felix de Souza': ['Pastoralidade'],
    'Nubia Fantini': ['Comunicação e Marketing'],
    'Nubia Paula Las Casas': ['Secretaria'],
    'Clovis Oliveira': ['CSA - BH'],
    'Marco Henrique': ['CSA - GZ'],
    'Ana Paula': ['CSA - DV'],
    'Paulo Negreiros': ['CSA - NL'],
    'Aparecida Debona': ['CSA - CTG'],
    'Renata Junqueira': ['CSA - BH'],
    'Mariana Esser': ['CSA - NL'],
    'Fernanda Diniz': ['CSA - GZ'],
    'Adriana Cassemira': ['CSA - CTG']
}