departamentos = [
    'CSA - BH',
    'CSA - CTG',
    'CSA - NL',
    'CSA - GZ',
    'CSA - DV',
    'EPSA',
    'AIACOM',
    'ESA',
    'Adeodato',
    'ILALI',
    "Contabilidade",
    'Financeiro',
    'Administrativo',
    'Suprimentos',
    "Assessoria Jurídica",
    'Gestão de Documentos',
    'Recursos Humanos',
    'Tecnologia da Informação',
    'Pastoralidade',
    'Comunicação e Marketing',
    'Estratégia e Novos Negócios',
    'Sustentabilidade',
    'Assistência Social',
    'Departamento de Pessoal',
    'Internacionalização',
    'Secretaria',
    'Coordenação de Manutenção'
]